id: 24b448713ed040598623f824a9ef14e2
initial_creation_type: ocr
source_metadata:
  volumes:
    aa84979640194d728dbd2be695445505:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: དཔལ་རྟ་མགྲིན་གྱི་སྒྲུབ་ཐབས།
      total_pages: 1044
      volume_number: 38
